### ISSUE TITLE
SQL Lite Interop Unable to Load error

### ISSUE THREAD

**Issue by haitheredavid** [specklesystems/speckle-sharp#846]
hi

hitting an issue with `SQLLite.Interop` when running the grasshopper connector off the [most recent commit](https://github.com/specklesystems/speckle-sharp/commit/f7dbdf3c84b78c5eb0847bdb260820df18600e14). I've done some quick trouble shooting of rebuilding and refreshing my local fork but no success 😢 

Below is the error message.

> System.DllNotFoundException: Unable to load DLL 'SQLite.Interop.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
>    at System.Data.SQLite.UnsafeNativeMethods.sqlite3_open_interop(Byte[] utf8Filename, Byte[] vfsName, SQLiteOpenFlagsEnum flags, Int32 extFuncs, IntPtr& db)
>    at System.Data.SQLite.SQLite3.Open(String strFilename, String vfsName, SQLiteConnectionFlags connectionFlags, SQLiteOpenFlagsEnum openFlags, Int32 maxPoolSize, Boolean usePool)
>    at System.Data.SQLite.SQLiteConnection.Open()

I checked the `bin` folder for ConnectorGrasshoper and it shows that `SQLite.Interop.dll` is being built, but when I drop the `Accounts` node in gh that error is thrown.

**Comment by izzylys** [comment]
hey there!

this issue crops up now and again and I'm not entirely sure what the cause is tbh. however, have you tried manually deleting all the `bin` and `obj` folders in core and the connector + converter (eg in `Core`, `ConnectorGrasshopper`, and `ConverterRhinoGh`) and rebuilding from scratch? you can also go into your `AppData/Speckle` folder and manually delete the object kits.

this combo usually seams to clean it up for me, so give it a try and see if it helps!

**Comment by haitheredavid** [comment]
@izzylys thanks for the speedy reply! I tried what you suggested but that didn't seem to clean up the issue. I ended up deleting the whole `speckle-sharp` repo and cloning it again, but that didn't seem to help :hurtrealbad:. Here are some potentially helpful notes around this issues I've noticed... 

- I refreshed my `speckle-sharp` repo today, and that lead to a discovery  of the new `Reports` field in the `ISpeckleConverter`. Since then I have been updating my codebase and hitting different issues along the way. Most ,if not all, of the issues had to do with my projects being out of sync with their converters. 
- Before I discovered this issue in gh I pushed all the updated libraries into my unity project and implemented the converter changes. I got a similar error there with the missing `SQLite.Interop.dll`, and noticed that the `core\bin` didn't include the `x64` or `x86` folder that contains that .dll. I thought it was something I messed up, so I dug it up and copied it into the unity project.  Funny enough, that seemed to fix things and my unity connector doesn't throw any errors...
-I'm currently working off of `Rhino 7`... I haven't had any issues in the past with this workflow thou but I figured I would mention that. 

Maybe I'll try uninstalling the manager and see if that resets things. If that doesn't work I'll try throwing my computer out the window.

**Comment by teocomi** [comment]
Hey David, can you confirm if you're getting this error when building the GH project or somewhere else?
We fixed it in the past by adding few lines of code in the csproj, but should not be needed as we cannot repro on our end,

**Comment by haitheredavid** [comment]
@teocomi confirming that I'm getting this error when building the gh connector. I only modified the `config template` so it will launch `Rhino7.exe`.  From the ConnectorGrasshopper solution I went through the process again this morning, here are the steps:

1. Deleted all `bin` and `obj` folders from `Core`, `Object`, and `ConnectorGrasshopper`
2. Deleted content from `AppData/Speckle`
3. Restored nugget packages 
4. Built solution 
5. Ran Debug build 
6. Throws Error when I try to access the `Account` node

For sanity sake, I repeated the same process without running `debug` with gh and hit the same error.  This is the [exact line ](https://github.com/specklesystems/speckle-sharp/blob/4a805270d548e2836ab4aa89575cc5f83bf2e6e1/Core/Core/Transports/SQLite.cs#L324)the error hits with an `unhandled exception`

**Comment by teocomi** [comment]
Hi David, I just tried again and we cannot replicate this issue internally.
I'm gonna close this isse but I have a few more things that you can do:

You could try adding these lines in your `csprog` inside the first `PropertyGroup`.

```
    <!--these four make so that the SQLite.Interop.dll is copied in the after build target-->
    <ContentSQLiteInteropFiles>true</ContentSQLiteInteropFiles>
    <CopySQLiteInteropFiles>false</CopySQLiteInteropFiles>
    <CleanSQLiteInteropFiles>false</CleanSQLiteInteropFiles>
    <CollectSQLiteInteropFiles>false</CollectSQLiteInteropFiles>
```

And you could set up a custom post build action that copies them to the bin folder manually.

**Comment by haitheredavid** [comment]
@teocomi just getting back from the 🍯 🌔, so I apologize for the delay in getting back to the crew.

I wanted to follow up on your last suggestion to wrap up the loose ends. I added those lines to the `csproj` along with the post build action, but that did not seem to fix the issue. Prior to adding to those lines `bin` had the `x86 / x64` folders with the `SQLite.Interop.dll` included. I'm still really confused on what makes this work vs the Unity version, but for now I am going to admit defeat and relay on the speckle manager and disable my `ConnectorGrasshopper` proj.

Thanks to you and @izzylys for trying to troubleshooting this issue.
